# Generated by Django 5.0 on 2023-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_purchaseordermodel_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseordermodel",
            name="delivery_date",
            field=models.DateTimeField(null=True),
        ),
    ]
