# Generated by Django 5.0 on 2023-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_purchaseordermodel_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseordermodel",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
